In [1]:
import numpy as np

In [2]:
myarr = np.array([3, 6, 32, 7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr = np.array([3, 6, 32, 7], np.int8)

In [5]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [6]:
myarr = np.array([3, 6, 377772, 7], np.int8)

In [7]:
myarr

array([  3,   6, -84,   7], dtype=int8)

In [8]:
myarr = np.array([[3, 6, 37, 7]], np.int64)

In [9]:
myarr[0][3]

7

In [10]:
myarr.shape

(1, 4)

In [11]:
myarr.dtype

dtype('int64')

In [12]:
myarr[0, 1] = 45

In [13]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

## Array creation : convertion from other python structure

In [14]:
listarray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])

In [15]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.size

9

In [19]:
np.array({34, 23, 23})

array({34, 23}, dtype=object)

In [20]:
zeros = np.zeros((2, 5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
zeros.shape

(2, 5)

In [24]:
rng = np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1, 5, 12)

In [27]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [28]:
l = np.linspace(1, 10, 4)

In [29]:
l

array([ 1.,  4.,  7., 10.])

In [30]:
emp = np.empty((4, 6))

In [31]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921279e-306, 1.15710427e-306, 7.56587585e-307],
       [1.37961302e-306, 6.23053614e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 2.22522597e-306,
        1.06810268e-306, 6.23052935e-307, 1.42421160e-306],
       [1.11261027e-306, 1.42418172e-306, 1.37961641e-306,
        1.39071445e-307, 8.45610231e-307, 1.78021527e-306]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [34]:
emp_like = np.empty_like(l)

In [35]:
emp_like

array([ 1.,  4.,  7., 10.])

In [36]:
ide = np.identity(45)

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
ide.shape

(45, 45)

In [39]:
arr = np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr = arr.reshape((3, 33))

In [44]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [45]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr = arr.ravel()

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr.shape

(99,)

In [49]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [50]:
ar = np.array(x)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.sum(axis = 0)

array([12,  8,  9])

In [53]:
ar.sum(axis = 1)

array([ 6, 15,  8])

In [54]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [55]:
ar.flat

In [56]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [57]:
ar.ndim

2

In [58]:
ar.size

9

In [59]:
ar.nbytes

36

In [60]:
one = np.array([1,3,4,634,2])

In [61]:
one.argmax()#return the index where the maximum element is present

3

In [62]:
one.argmin()#return the index where the minimum element is present

0

In [63]:
one.argsort()# argsort gives us an arry which says if we sort the arrqay what will e ous=r index

array([0, 4, 1, 2, 3], dtype=int64)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
ar.argmin()

8

In [66]:
ar.argmax()

6

In [67]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [68]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [69]:
ar.argsort(axis = 0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [70]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [71]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [72]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [73]:
ar.size

9

In [74]:
ar.shape

(3, 3)

In [75]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [76]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [77]:
ar2 = np.array([[1, 2, 1], [4, 0, 6], [8, 1, 0]])

In [78]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [80]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [81]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [83]:
ar.sum()

29

In [84]:
ar.min()

0

In [85]:
ar.max()

7

In [86]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [87]:
type(np.where(ar>5))

tuple

In [88]:
np.count_nonzero(ar)

8

In [89]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
ar.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [91]:
ar[1, 2] = 0

In [92]:
ar.nonzero()

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [93]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

In [94]:
import sys

In [95]:
py_ar = [0, 4, 55, 2]

In [96]:
np_ar = np.array(py_ar)

In [97]:
sys.getsizeof(1) * len(py_ar)

112

In [98]:
np_ar.itemsize * np_ar.size

16

In [99]:
np_ar.tolist()

[0, 4, 55, 2]

In [100]:
#above is the basic of numpy